CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_admin BOOLEAN NOT NULL DEFAULT false
);

-- 添加用户关联到现有表
ALTER TABLE scenes ADD COLUMN user_id INTEGER REFERENCES users(id);
ALTER TABLE performers ADD COLUMN user_id INTEGER REFERENCES users(id);
ALTER TABLE studios ADD COLUMN user_id INTEGER REFERENCES users(id);
ALTER TABLE tags ADD COLUMN user_id INTEGER REFERENCES users(id);
ALTER TABLE galleries ADD COLUMN user_id INTEGER REFERENCES users(id);
ALTER TABLE images ADD COLUMN user_id INTEGER REFERENCES users(id);
ALTER TABLE groups ADD COLUMN user_id INTEGER REFERENCES users(id); 